### ISSUE TITLE
[BUG]motion module fail when build from source

### ISSUE THREAD

**Issue by longwoo** [jetsonhacks/installRealSenseSDK#5]
Problem solved after I updated the firmware to 05.12.03.00.

======================================================================

**Describe the issue**
Please describe the issue
When install from prebuild  `installLibrealsense.sh`, everything is OK. BUT, When install from source `buildLibrealsense.sh`, the realsensen-viewer gives motion module fail  warning. The reason why I build from source is there is no pybinding in  `installLibrealsense.sh`.

**What version of L4T/JetPack**
L4T/JetPack version: JetPack4.3 with Xavier

**Which Intel RealSense camera(s)**
RealSense camera(s):435i

**To Reproduce**
realsensen-viewer

**Expected behavior**
No warning information show on the screen.

**Additional context**
The warning is missing, after I updated the firmware to 05.12.03.00

**Comment by Andrew5c** [comment]
yes, @longwoo ,I have the same problem as you. what I used is Jetson Nano.
what I meet is the following:
1. I install the librealsense successfully follow the guides of great Jetsonhacks, by run the `./installlibrealsense.sh`, and I run the `realsense-viewer` successfully. but the problem is that I don't see the SDK.
2. After that, I run the `sudo apt remove librealsense2` to remove the above install for next build. And I success to remove it.
3. Then I run the `./buildlibrealsense.sh` in Jetsonhacks github: [https://github.com/JetsonHacksNano/installLibrealsense/blob/master/buildLibrealsense.sh](https://github.com/JetsonHacksNano/installLibrealsense/blob/master/buildLibrealsense.sh)
. and again successfully builded. But the problem is **when I run the realsense-viewer, and plug the T265 in Nano, it show nothing! no picture, no device. not like the case in STEP 1!!**
have you solved your problem? and can you tell me your method? Thanks very much.

**Comment by longwoo** [comment]
@Andrew5c 
1. `./installlibrealsense.sh` is enough if you don't need pyrealsense. You can build a project with the help of Cmake.

```
cmake_minimum_required(VERSION 3.1.0)
project(Realsense2Minimal)
set(CMAKE_BUILD_TYPE Debug)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O0 -std=c++11")

find_package(realsense2 REQUIRED)
set(DEPENDENCIES realsense2)

add_executable(main main.cpp)
target_link_libraries(main ${DEPENDENCIES})
```

2. If you really need build from source, you should check if all software version match, such as Jetpack, realsesen2 sdk version , and firmware. I can't check your issue since no  Nano and   T265 at hand .

**Comment by Andrew5c** [comment]
@longwoo ，thanks for your advice! 
Now, I want to install the librealsense by `./installlibrealsense.sh` again. But the question is I have run the `./buildlibrealsense.sh` in my nano, Should I delete the files created by build operation? or just run the `./installlibrealsense.sh` again directly?

**Comment by longwoo** [comment]
@Andrew5c Yes, uninstall first ,or you may meet multiple realsense2 lib problem when using cmake `find_package` .Go to the `librealsense/build` path, and `sudo make uninstall`.

**Comment by Andrew5c** [comment]
@longwoo Hi, bro, sorry to trouble your again.
1. thanks to your advice, I run the `./installlibrealsense.sh` again and have installed the librealsense successfully. 
2. And then I run the `git clone https://github.com/IntelRealSense/librealsense.git` to get the SDK, what makes me confused is that, I find the downloaded version is **2.32.1**, However the latest version in offical librealsense github is **2.34.0**. why is that?
3. Now I want to install realsense-ros, however no version of realsense-ros is match with Librealsense SDK 2.32.1, which is downloaded by me. 
4. So, the question is what can I do to get a different librealsense SDK so that I can install the realsense-ros. Delete the SDK in my Ubuntu and clone a new one?

Thanks whatever!!

(by the way, can you give me your email so that we can communicate more conveniently? 👍  )
